set_property SRC_FILE_INFO {cfile:{C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/constrs_1/imports/example_design/ac701_ethernet_rgmii_example_design.xdc} rfile:../../../../ac701_ethernet_rgmii_example.srcs/constrs_1/imports/example_design/ac701_ethernet_rgmii_example_design.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R3 [get_ports clk_in_p]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P3 [get_ports clk_in_n]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U4 [get_ports glbl_rst]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T25 [get_ports activity_flash]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R26 [get_ports activity_flashn]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U6 [get_ports update_speed]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R5 [get_ports config_board]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U5 [get_ports pause_req_s]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P6 [get_ports reset_error]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R8 [get_ports {mac_speed[0]}]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P8 [get_ports {mac_speed[1]}]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R7 [get_ports gen_tx_data]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R6 [get_ports chk_tx_data]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V18 [get_ports phy_resetn]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE25 [get_ports serial_response]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE26 [get_ports tx_statistics_s]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC22 [get_ports rx_statistics_s]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W18 [get_ports mdc]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T14 [get_ports mdio]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V14 [get_ports {rgmii_rxd[3]}]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports {rgmii_rxd[2]}]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {rgmii_rxd[1]}]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U17 [get_ports {rgmii_rxd[0]}]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T17 [get_ports {rgmii_txd[3]}]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T18 [get_ports {rgmii_txd[2]}]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U15 [get_ports {rgmii_txd[1]}]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {rgmii_txd[0]}]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T15 [get_ports rgmii_tx_ctl]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U22 [get_ports rgmii_txc]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U14 [get_ports rgmii_rx_ctl]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U21 [get_ports rgmii_rxc]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F5 [get_ports gtx_clk_bufg_out]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_in_p 0.050
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_ports update_speed] 4.000
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_ports mdio] -to [get_cells -hier -filter {NAME =~ *managen/mdio_enabled.phy/mdio_in_reg1_reg}] 16.000
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *rx_fifo_i/rd_addr_reg[*]}] -to [get_cells -hier -filter {name =~ *fifo*wr_rd_addr_reg[*]}] 6.000
set_property src_info {type:XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *rx_fifo_i/wr_store_frame_tog_reg}] -to [get_cells -hier -filter {name =~ *fifo_i/resync_wr_store_frame_tog/data_sync_reg0}] 6.000
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *rx_fifo_i/update_addr_tog_reg}] -to [get_cells -hier -filter {name =~ *rx_fifo_i/sync_rd_addr_tog/data_sync_reg0}] 6.000
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *tx_fifo_i/rd_addr_txfer_reg[*]}] -to [get_cells -hier -filter {name =~ *fifo*wr_rd_addr_reg[*]}] 6.000
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *tx_fifo_i/wr_frame_in_fifo_reg}] -to [get_cells -hier -filter {name =~ *tx_fifo_i/resync_wr_frame_in_fifo/data_sync_reg0}] 6.000
set_property src_info {type:XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *tx_fifo_i/wr_frames_in_fifo_reg}] -to [get_cells -hier -filter {name =~ *tx_fifo_i/resync_wr_frames_in_fifo/data_sync_reg0}] 6.000
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *tx_fifo_i/frame_in_fifo_valid_tog_reg}] -to [get_cells -hier -filter {name =~ *tx_fifo_i/resync_fif_valid_tog/data_sync_reg0}] 6.000
set_property src_info {type:XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *tx_fifo_i/rd_txfer_tog_reg}] -to [get_cells -hier -filter {name =~ *tx_fifo_i/resync_rd_txfer_tog/data_sync_reg0}] 6.000
set_property src_info {type:XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_cells -hier -filter {name =~ *tx_fifo_i/rd_tran_frame_tog_reg}] -to [get_cells -hier -filter {name =~ *tx_fifo_i/resync_rd_tran_frame_tog/data_sync_reg0}] 6.000
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F20 [get_ports BUS_REGCLR]
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J20 [get_ports BUSA_WR_ADDRCLR]
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G19 [get_ports BUSA_RD_ENA]
set_property src_info {type:XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G15 [get_ports {BUSA_RD_ROWSEL_S[0]}]
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F15 [get_ports {BUSA_RD_ROWSEL_S[1]}]
set_property src_info {type:XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E16 [get_ports {BUSA_RD_ROWSEL_S[2]}]
set_property src_info {type:XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F24 [get_ports {BUSA_RD_COLSEL_S[0]}]
set_property src_info {type:XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G24 [get_ports {BUSA_RD_COLSEL_S[1]}]
set_property src_info {type:XDC file:1 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E23 [get_ports {BUSA_RD_COLSEL_S[2]}]
set_property src_info {type:XDC file:1 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F23 [get_ports {BUSA_RD_COLSEL_S[3]}]
set_property src_info {type:XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H24 [get_ports {BUSA_RD_COLSEL_S[4]}]
set_property src_info {type:XDC file:1 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J24 [get_ports {BUSA_RD_COLSEL_S[5]}]
set_property src_info {type:XDC file:1 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D20 [get_ports BUSA_CLR]
set_property src_info {type:XDC file:1 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B19 [get_ports BUSA_RAMP]
set_property src_info {type:XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F22 [get_ports {BUSA_SAMPLESEL_S[0]}]
set_property src_info {type:XDC file:1 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J21 [get_ports {BUSA_SAMPLESEL_S[1]}]
set_property src_info {type:XDC file:1 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K20 [get_ports {BUSA_SAMPLESEL_S[2]}]
set_property src_info {type:XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G20 [get_ports {BUSA_SAMPLESEL_S[3]}]
set_property src_info {type:XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G21 [get_ports {BUSA_SAMPLESEL_S[4]}]
set_property src_info {type:XDC file:1 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M17 [get_ports BUSA_SR_CLEAR]
set_property src_info {type:XDC file:1 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A22 [get_ports BUSA_SR_SEL]
set_property src_info {type:XDC file:1 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A19 [get_ports {BUSA_DO[0]}]
set_property src_info {type:XDC file:1 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B22 [get_ports {BUSA_DO[1]}]
set_property src_info {type:XDC file:1 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D21 [get_ports {BUSA_DO[2]}]
set_property src_info {type:XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M16 [get_ports {BUSA_DO[3]}]
set_property src_info {type:XDC file:1 line:252 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D16 [get_ports {BUSA_DO[4]}]
set_property src_info {type:XDC file:1 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B20 [get_ports {BUSA_DO[5]}]
set_property src_info {type:XDC file:1 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A17 [get_ports {BUSA_DO[6]}]
set_property src_info {type:XDC file:1 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A18 [get_ports {BUSA_DO[7]}]
set_property src_info {type:XDC file:1 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L17 [get_ports {BUSA_DO[8]}]
set_property src_info {type:XDC file:1 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A20 [get_ports {BUSA_DO[9]}]
set_property src_info {type:XDC file:1 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K21 [get_ports {BUSA_DO[10]}]
set_property src_info {type:XDC file:1 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C21 [get_ports {BUSA_DO[11]}]
set_property src_info {type:XDC file:1 line:260 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B21 [get_ports {BUSA_DO[12]}]
set_property src_info {type:XDC file:1 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L14 [get_ports {BUSA_DO[13]}]
set_property src_info {type:XDC file:1 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J19 [get_ports {BUSA_DO[14]}]
set_property src_info {type:XDC file:1 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L18 [get_ports {BUSA_DO[15]}]
set_property src_info {type:XDC file:1 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F25 [get_ports SIN]
set_property src_info {type:XDC file:1 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G26 [get_ports PCLK]
set_property src_info {type:XDC file:1 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H26 [get_ports SHOUT]
set_property src_info {type:XDC file:1 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G25 [get_ports SCLK]
set_property src_info {type:XDC file:1 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H18 [get_ports WL_CLK_N]
set_property src_info {type:XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J18 [get_ports WL_CLK_P]
set_property src_info {type:XDC file:1 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K23 [get_ports WR1_ENA]
set_property src_info {type:XDC file:1 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K22 [get_ports WR2_ENA]
set_property src_info {type:XDC file:1 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H15 [get_ports SSTIN_N]
set_property src_info {type:XDC file:1 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H14 [get_ports SSTIN_P]
set_property src_info {type:XDC file:1 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14 [get_ports SR_CLOCK]
set_property src_info {type:XDC file:1 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G22 [get_ports SAMPLESEL_ANY]
set_property src_info {type:XDC file:1 line:276 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B17 [get_ports {TDC1_TRG[0]}]
set_property src_info {type:XDC file:1 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E20 [get_ports {TDC1_TRG[1]}]
set_property src_info {type:XDC file:1 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D26 [get_ports {TDC1_TRG[2]}]
set_property src_info {type:XDC file:1 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E26 [get_ports {TDC1_TRG[3]}]
set_property src_info {type:XDC file:1 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D25 [get_ports {TDC1_TRG[4]}]
set_property src_info {type:XDC file:1 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G17 [get_ports DAC_SCL]
set_property src_info {type:XDC file:1 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F17 [get_ports DAC_SDA]
set_property src_info {type:XDC file:1 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T8 [get_ports SMP_EXTSYNC]
set_property src_info {type:XDC file:1 line:952 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:953 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:954 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:955 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:956 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 16384 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:957 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:958 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:959 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:960 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:961 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:962 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list clkgen_1/inst/clk_out1]]
set_property src_info {type:XDC file:1 line:963 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:964 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:965 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {u_WaveformPedcalcDSP/ped_sa_num[0]} {u_WaveformPedcalcDSP/ped_sa_num[1]} {u_WaveformPedcalcDSP/ped_sa_num[2]} {u_WaveformPedcalcDSP/ped_sa_num[3]} {u_WaveformPedcalcDSP/ped_sa_num[4]} {u_WaveformPedcalcDSP/ped_sa_num[5]} {u_WaveformPedcalcDSP/ped_sa_num[6]} {u_WaveformPedcalcDSP/ped_sa_num[7]} {u_WaveformPedcalcDSP/ped_sa_num[8]} {u_WaveformPedcalcDSP/ped_sa_num[9]} {u_WaveformPedcalcDSP/ped_sa_num[10]} {u_WaveformPedcalcDSP/ped_sa_num[11]} {u_WaveformPedcalcDSP/ped_sa_num[12]} {u_WaveformPedcalcDSP/ped_sa_num[19]} {u_WaveformPedcalcDSP/ped_sa_num[20]} {u_WaveformPedcalcDSP/ped_sa_num[21]}]]
set_property src_info {type:XDC file:1 line:966 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:967 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:968 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 17 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:969 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {u_WaveformPedcalcDSP/wval0temp[0]} {u_WaveformPedcalcDSP/wval0temp[1]} {u_WaveformPedcalcDSP/wval0temp[2]} {u_WaveformPedcalcDSP/wval0temp[3]} {u_WaveformPedcalcDSP/wval0temp[4]} {u_WaveformPedcalcDSP/wval0temp[5]} {u_WaveformPedcalcDSP/wval0temp[6]} {u_WaveformPedcalcDSP/wval0temp[7]} {u_WaveformPedcalcDSP/wval0temp[8]} {u_WaveformPedcalcDSP/wval0temp[9]} {u_WaveformPedcalcDSP/wval0temp[10]} {u_WaveformPedcalcDSP/wval0temp[11]} {u_WaveformPedcalcDSP/wval0temp[12]} {u_WaveformPedcalcDSP/wval0temp[13]} {u_WaveformPedcalcDSP/wval0temp[14]} {u_WaveformPedcalcDSP/wval0temp[15]} {u_WaveformPedcalcDSP/wval0temp[16]}]]
set_property src_info {type:XDC file:1 line:970 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:971 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:972 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 12 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:973 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {u_WaveformPedcalcDSP/ped_sa_wval0[0]} {u_WaveformPedcalcDSP/ped_sa_wval0[1]} {u_WaveformPedcalcDSP/ped_sa_wval0[2]} {u_WaveformPedcalcDSP/ped_sa_wval0[3]} {u_WaveformPedcalcDSP/ped_sa_wval0[4]} {u_WaveformPedcalcDSP/ped_sa_wval0[5]} {u_WaveformPedcalcDSP/ped_sa_wval0[6]} {u_WaveformPedcalcDSP/ped_sa_wval0[7]} {u_WaveformPedcalcDSP/ped_sa_wval0[8]} {u_WaveformPedcalcDSP/ped_sa_wval0[9]} {u_WaveformPedcalcDSP/ped_sa_wval0[10]} {u_WaveformPedcalcDSP/ped_sa_wval0[11]}]]
set_property src_info {type:XDC file:1 line:974 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:975 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:976 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:977 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {u_WaveformPedcalcDSP/ped_win[0]} {u_WaveformPedcalcDSP/ped_win[1]}]]
set_property src_info {type:XDC file:1 line:978 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:979 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:980 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 9 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:981 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {u_WaveformPedcalcDSP/win_addr_start_i[0]} {u_WaveformPedcalcDSP/win_addr_start_i[1]} {u_WaveformPedcalcDSP/win_addr_start_i[2]} {u_WaveformPedcalcDSP/win_addr_start_i[3]} {u_WaveformPedcalcDSP/win_addr_start_i[4]} {u_WaveformPedcalcDSP/win_addr_start_i[5]} {u_WaveformPedcalcDSP/win_addr_start_i[6]} {u_WaveformPedcalcDSP/win_addr_start_i[7]} {u_WaveformPedcalcDSP/win_addr_start_i[8]}]]
set_property src_info {type:XDC file:1 line:982 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:983 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:984 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 12 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:985 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {u_WaveformPedcalcDSP/ped_sa_wval1[0]} {u_WaveformPedcalcDSP/ped_sa_wval1[1]} {u_WaveformPedcalcDSP/ped_sa_wval1[2]} {u_WaveformPedcalcDSP/ped_sa_wval1[3]} {u_WaveformPedcalcDSP/ped_sa_wval1[4]} {u_WaveformPedcalcDSP/ped_sa_wval1[5]} {u_WaveformPedcalcDSP/ped_sa_wval1[6]} {u_WaveformPedcalcDSP/ped_sa_wval1[7]} {u_WaveformPedcalcDSP/ped_sa_wval1[8]} {u_WaveformPedcalcDSP/ped_sa_wval1[9]} {u_WaveformPedcalcDSP/ped_sa_wval1[10]} {u_WaveformPedcalcDSP/ped_sa_wval1[11]}]]
set_property src_info {type:XDC file:1 line:986 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:987 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:988 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 17 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:989 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {u_WaveformPedcalcDSP/wval1temp[0]} {u_WaveformPedcalcDSP/wval1temp[1]} {u_WaveformPedcalcDSP/wval1temp[2]} {u_WaveformPedcalcDSP/wval1temp[3]} {u_WaveformPedcalcDSP/wval1temp[4]} {u_WaveformPedcalcDSP/wval1temp[5]} {u_WaveformPedcalcDSP/wval1temp[6]} {u_WaveformPedcalcDSP/wval1temp[7]} {u_WaveformPedcalcDSP/wval1temp[8]} {u_WaveformPedcalcDSP/wval1temp[9]} {u_WaveformPedcalcDSP/wval1temp[10]} {u_WaveformPedcalcDSP/wval1temp[11]} {u_WaveformPedcalcDSP/wval1temp[12]} {u_WaveformPedcalcDSP/wval1temp[13]} {u_WaveformPedcalcDSP/wval1temp[14]} {u_WaveformPedcalcDSP/wval1temp[15]} {u_WaveformPedcalcDSP/wval1temp[16]}]]
set_property src_info {type:XDC file:1 line:990 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:991 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:992 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:993 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {u_WaveformPedcalcDSP/ped_ch[0]} {u_WaveformPedcalcDSP/ped_ch[1]} {u_WaveformPedcalcDSP/ped_ch[2]} {u_WaveformPedcalcDSP/ped_ch[3]}]]
set_property src_info {type:XDC file:1 line:994 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:995 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:996 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 6 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:997 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {u_WaveformPedcalcDSP/dmx_st[0]} {u_WaveformPedcalcDSP/dmx_st[1]} {u_WaveformPedcalcDSP/dmx_st[2]} {u_WaveformPedcalcDSP/dmx_st[3]} {u_WaveformPedcalcDSP/dmx_st[4]} {u_WaveformPedcalcDSP/dmx_st[5]}]]
set_property src_info {type:XDC file:1 line:998 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:999 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:1000 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 5 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:1001 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list {u_WaveformPedcalcDSP/count[0]} {u_WaveformPedcalcDSP/count[1]} {u_WaveformPedcalcDSP/count[2]} {u_WaveformPedcalcDSP/count[3]} {u_WaveformPedcalcDSP/count[4]}]]
set_property src_info {type:XDC file:1 line:1002 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1003 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:1004 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 20 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:1005 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list {u_SerialDataRoutDemux/u_bram2/doutb[0]} {u_SerialDataRoutDemux/u_bram2/doutb[1]} {u_SerialDataRoutDemux/u_bram2/doutb[2]} {u_SerialDataRoutDemux/u_bram2/doutb[3]} {u_SerialDataRoutDemux/u_bram2/doutb[4]} {u_SerialDataRoutDemux/u_bram2/doutb[5]} {u_SerialDataRoutDemux/u_bram2/doutb[6]} {u_SerialDataRoutDemux/u_bram2/doutb[7]} {u_SerialDataRoutDemux/u_bram2/doutb[8]} {u_SerialDataRoutDemux/u_bram2/doutb[9]} {u_SerialDataRoutDemux/u_bram2/doutb[10]} {u_SerialDataRoutDemux/u_bram2/doutb[11]} {u_SerialDataRoutDemux/u_bram2/doutb[12]} {u_SerialDataRoutDemux/u_bram2/doutb[13]} {u_SerialDataRoutDemux/u_bram2/doutb[14]} {u_SerialDataRoutDemux/u_bram2/doutb[15]} {u_SerialDataRoutDemux/u_bram2/doutb[16]} {u_SerialDataRoutDemux/u_bram2/doutb[17]} {u_SerialDataRoutDemux/u_bram2/doutb[18]} {u_SerialDataRoutDemux/u_bram2/doutb[19]}]]
set_property src_info {type:XDC file:1 line:1006 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1007 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:1008 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 11 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:1009 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list {u_SerialDataRoutDemux/u_bram2/addrb[0]} {u_SerialDataRoutDemux/u_bram2/addrb[1]} {u_SerialDataRoutDemux/u_bram2/addrb[2]} {u_SerialDataRoutDemux/u_bram2/addrb[3]} {u_SerialDataRoutDemux/u_bram2/addrb[4]} {u_SerialDataRoutDemux/u_bram2/addrb[5]} {u_SerialDataRoutDemux/u_bram2/addrb[6]} {u_SerialDataRoutDemux/u_bram2/addrb[7]} {u_SerialDataRoutDemux/u_bram2/addrb[8]} {u_SerialDataRoutDemux/u_bram2/addrb[9]} {u_SerialDataRoutDemux/u_bram2/addrb[10]}]]
set_property src_info {type:XDC file:1 line:1010 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1011 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:1012 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 20 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:1013 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list {SRAM_1/addra[0]} {SRAM_1/addra[1]} {SRAM_1/addra[2]} {SRAM_1/addra[3]} {SRAM_1/addra[4]} {SRAM_1/addra[5]} {SRAM_1/addra[6]} {SRAM_1/addra[7]} {SRAM_1/addra[8]} {SRAM_1/addra[9]} {SRAM_1/addra[10]} {SRAM_1/addra[11]} {SRAM_1/addra[12]} {SRAM_1/addra[13]} {SRAM_1/addra[14]} {SRAM_1/addra[15]} {SRAM_1/addra[16]} {SRAM_1/addra[17]} {SRAM_1/addra[18]} {SRAM_1/addra[19]}]]
set_property src_info {type:XDC file:1 line:1014 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1015 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:1016 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:1017 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list {SRAM_1/dina[0]} {SRAM_1/dina[1]} {SRAM_1/dina[2]} {SRAM_1/dina[3]} {SRAM_1/dina[4]} {SRAM_1/dina[5]} {SRAM_1/dina[6]} {SRAM_1/dina[7]}]]
set_property src_info {type:XDC file:1 line:1018 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1019 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:1020 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:1021 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list {SRAM_1/douta[0]} {SRAM_1/douta[1]} {SRAM_1/douta[2]} {SRAM_1/douta[3]} {SRAM_1/douta[4]} {SRAM_1/douta[5]} {SRAM_1/douta[6]} {SRAM_1/douta[7]}]]
set_property src_info {type:XDC file:1 line:1022 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1023 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:1024 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 5 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:1025 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list {u_wavepedsub/count[0]} {u_wavepedsub/count[1]} {u_wavepedsub/count[2]} {u_wavepedsub/count[3]} {u_wavepedsub/count[4]}]]
set_property src_info {type:XDC file:1 line:1026 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1027 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:1 line:1028 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 5 [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:1 line:1029 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list {u_wavepedsub/next_ped_st[0]} {u_wavepedsub/next_ped_st[1]} {u_wavepedsub/next_ped_st[2]} {u_wavepedsub/next_ped_st[3]} {u_wavepedsub/next_ped_st[4]}]]
set_property src_info {type:XDC file:1 line:1030 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1031 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:1 line:1032 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:1 line:1033 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list {u_wavepedsub/ped_ch[0]} {u_wavepedsub/ped_ch[1]} {u_wavepedsub/ped_ch[2]} {u_wavepedsub/ped_ch[3]}]]
set_property src_info {type:XDC file:1 line:1034 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1035 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:1 line:1036 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 5 [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:1 line:1037 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe18 [get_nets [list {u_wavepedsub/ped_sa[0]} {u_wavepedsub/ped_sa[1]} {u_wavepedsub/ped_sa[2]} {u_wavepedsub/ped_sa[3]} {u_wavepedsub/ped_sa[4]}]]
set_property src_info {type:XDC file:1 line:1038 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1039 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:1 line:1040 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 22 [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:1 line:1041 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe19 [get_nets [list {u_wavepedsub/ped_sa_num[0]} {u_wavepedsub/ped_sa_num[1]} {u_wavepedsub/ped_sa_num[2]} {u_wavepedsub/ped_sa_num[3]} {u_wavepedsub/ped_sa_num[4]} {u_wavepedsub/ped_sa_num[5]} {u_wavepedsub/ped_sa_num[6]} {u_wavepedsub/ped_sa_num[7]} {u_wavepedsub/ped_sa_num[8]} {u_wavepedsub/ped_sa_num[9]} {u_wavepedsub/ped_sa_num[10]} {u_wavepedsub/ped_sa_num[11]} {u_wavepedsub/ped_sa_num[12]} {u_wavepedsub/ped_sa_num[13]} {u_wavepedsub/ped_sa_num[14]} {u_wavepedsub/ped_sa_num[15]} {u_wavepedsub/ped_sa_num[16]} {u_wavepedsub/ped_sa_num[17]} {u_wavepedsub/ped_sa_num[18]} {u_wavepedsub/ped_sa_num[19]} {u_wavepedsub/ped_sa_num[20]} {u_wavepedsub/ped_sa_num[21]}]]
set_property src_info {type:XDC file:1 line:1042 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1043 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:1 line:1044 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:1 line:1045 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe20 [get_nets [list {u_wavepedsub/ped_win[0]} {u_wavepedsub/ped_win[1]}]]
set_property src_info {type:XDC file:1 line:1046 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1047 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:1 line:1048 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 12 [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:1 line:1049 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe21 [get_nets [list {u_wavepedsub/rval0[0]} {u_wavepedsub/rval0[1]} {u_wavepedsub/rval0[2]} {u_wavepedsub/rval0[3]} {u_wavepedsub/rval0[4]} {u_wavepedsub/rval0[5]} {u_wavepedsub/rval0[6]} {u_wavepedsub/rval0[7]} {u_wavepedsub/rval0[8]} {u_wavepedsub/rval0[9]} {u_wavepedsub/rval0[10]} {u_wavepedsub/rval0[11]}]]
set_property src_info {type:XDC file:1 line:1050 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1051 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:1 line:1052 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 12 [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:1 line:1053 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe22 [get_nets [list {u_wavepedsub/rval1[0]} {u_wavepedsub/rval1[1]} {u_wavepedsub/rval1[2]} {u_wavepedsub/rval1[3]} {u_wavepedsub/rval1[4]} {u_wavepedsub/rval1[5]} {u_wavepedsub/rval1[6]} {u_wavepedsub/rval1[7]} {u_wavepedsub/rval1[8]} {u_wavepedsub/rval1[9]} {u_wavepedsub/rval1[10]} {u_wavepedsub/rval1[11]}]]
set_property src_info {type:XDC file:1 line:1054 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1055 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property src_info {type:XDC file:1 line:1056 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 9 [get_debug_ports u_ila_0/probe23]
set_property src_info {type:XDC file:1 line:1057 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe23 [get_nets [list {u_wavepedsub/win_addr_start_i[0]} {u_wavepedsub/win_addr_start_i[1]} {u_wavepedsub/win_addr_start_i[2]} {u_wavepedsub/win_addr_start_i[3]} {u_wavepedsub/win_addr_start_i[4]} {u_wavepedsub/win_addr_start_i[5]} {u_wavepedsub/win_addr_start_i[6]} {u_wavepedsub/win_addr_start_i[7]} {u_wavepedsub/win_addr_start_i[8]}]]
set_property src_info {type:XDC file:1 line:1058 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1059 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property src_info {type:XDC file:1 line:1060 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 12 [get_debug_ports u_ila_0/probe24]
set_property src_info {type:XDC file:1 line:1061 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe24 [get_nets [list {u_SerialDataRoutDemux/dmx_wav[1][0]} {u_SerialDataRoutDemux/dmx_wav[1][1]} {u_SerialDataRoutDemux/dmx_wav[1][2]} {u_SerialDataRoutDemux/dmx_wav[1][3]} {u_SerialDataRoutDemux/dmx_wav[1][4]} {u_SerialDataRoutDemux/dmx_wav[1][5]} {u_SerialDataRoutDemux/dmx_wav[1][6]} {u_SerialDataRoutDemux/dmx_wav[1][7]} {u_SerialDataRoutDemux/dmx_wav[1][8]} {u_SerialDataRoutDemux/dmx_wav[1][9]} {u_SerialDataRoutDemux/dmx_wav[1][10]} {u_SerialDataRoutDemux/dmx_wav[1][11]}]]
set_property src_info {type:XDC file:1 line:1062 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1063 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property src_info {type:XDC file:1 line:1064 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
set_property src_info {type:XDC file:1 line:1065 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe25 [get_nets [list {u_wavepedsub/u_pedarr/wea[0]}]]
set_property src_info {type:XDC file:1 line:1066 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1067 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property src_info {type:XDC file:1 line:1068 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 12 [get_debug_ports u_ila_0/probe26]
set_property src_info {type:XDC file:1 line:1069 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe26 [get_nets [list {u_wavepedsub/u_pedarr/dina[0]} {u_wavepedsub/u_pedarr/dina[1]} {u_wavepedsub/u_pedarr/dina[2]} {u_wavepedsub/u_pedarr/dina[3]} {u_wavepedsub/u_pedarr/dina[4]} {u_wavepedsub/u_pedarr/dina[5]} {u_wavepedsub/u_pedarr/dina[6]} {u_wavepedsub/u_pedarr/dina[7]} {u_wavepedsub/u_pedarr/dina[8]} {u_wavepedsub/u_pedarr/dina[9]} {u_wavepedsub/u_pedarr/dina[10]} {u_wavepedsub/u_pedarr/dina[11]}]]
set_property src_info {type:XDC file:1 line:1070 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1071 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property src_info {type:XDC file:1 line:1072 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 20 [get_debug_ports u_ila_0/probe27]
set_property src_info {type:XDC file:1 line:1073 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe27 [get_nets [list {u_SerialDataRoutDemux/u_srout_bram/doutb[0]} {u_SerialDataRoutDemux/u_srout_bram/doutb[1]} {u_SerialDataRoutDemux/u_srout_bram/doutb[2]} {u_SerialDataRoutDemux/u_srout_bram/doutb[3]} {u_SerialDataRoutDemux/u_srout_bram/doutb[4]} {u_SerialDataRoutDemux/u_srout_bram/doutb[5]} {u_SerialDataRoutDemux/u_srout_bram/doutb[6]} {u_SerialDataRoutDemux/u_srout_bram/doutb[7]} {u_SerialDataRoutDemux/u_srout_bram/doutb[8]} {u_SerialDataRoutDemux/u_srout_bram/doutb[9]} {u_SerialDataRoutDemux/u_srout_bram/doutb[10]} {u_SerialDataRoutDemux/u_srout_bram/doutb[11]} {u_SerialDataRoutDemux/u_srout_bram/doutb[12]} {u_SerialDataRoutDemux/u_srout_bram/doutb[13]} {u_SerialDataRoutDemux/u_srout_bram/doutb[14]} {u_SerialDataRoutDemux/u_srout_bram/doutb[15]} {u_SerialDataRoutDemux/u_srout_bram/doutb[16]} {u_SerialDataRoutDemux/u_srout_bram/doutb[17]} {u_SerialDataRoutDemux/u_srout_bram/doutb[18]} {u_SerialDataRoutDemux/u_srout_bram/doutb[19]}]]
set_property src_info {type:XDC file:1 line:1074 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1075 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property src_info {type:XDC file:1 line:1076 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 11 [get_debug_ports u_ila_0/probe28]
set_property src_info {type:XDC file:1 line:1077 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe28 [get_nets [list {u_wavepedsub/u_pedarr/addra[0]} {u_wavepedsub/u_pedarr/addra[1]} {u_wavepedsub/u_pedarr/addra[2]} {u_wavepedsub/u_pedarr/addra[3]} {u_wavepedsub/u_pedarr/addra[4]} {u_wavepedsub/u_pedarr/addra[5]} {u_wavepedsub/u_pedarr/addra[6]} {u_wavepedsub/u_pedarr/addra[7]} {u_wavepedsub/u_pedarr/addra[8]} {u_wavepedsub/u_pedarr/addra[9]} {u_wavepedsub/u_pedarr/addra[10]}]]
set_property src_info {type:XDC file:1 line:1078 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1079 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property src_info {type:XDC file:1 line:1080 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 11 [get_debug_ports u_ila_0/probe29]
set_property src_info {type:XDC file:1 line:1081 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe29 [get_nets [list {u_SerialDataRoutDemux/u_srout_bram/addrb[0]} {u_SerialDataRoutDemux/u_srout_bram/addrb[1]} {u_SerialDataRoutDemux/u_srout_bram/addrb[2]} {u_SerialDataRoutDemux/u_srout_bram/addrb[3]} {u_SerialDataRoutDemux/u_srout_bram/addrb[4]} {u_SerialDataRoutDemux/u_srout_bram/addrb[5]} {u_SerialDataRoutDemux/u_srout_bram/addrb[6]} {u_SerialDataRoutDemux/u_srout_bram/addrb[7]} {u_SerialDataRoutDemux/u_srout_bram/addrb[8]} {u_SerialDataRoutDemux/u_srout_bram/addrb[9]} {u_SerialDataRoutDemux/u_srout_bram/addrb[10]}]]
set_property src_info {type:XDC file:1 line:1082 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1083 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property src_info {type:XDC file:1 line:1084 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
set_property src_info {type:XDC file:1 line:1085 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe30 [get_nets [list u_WaveformPedcalcDSP/update]]
set_property src_info {type:XDC file:1 line:1086 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1087 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property src_info {type:XDC file:1 line:1088 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe31]
set_property src_info {type:XDC file:1 line:1089 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe31 [get_nets [list u_wavepedsub/update]]
set_property src_info {type:XDC file:1 line:1090 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:1091 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:1092 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:1093 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets CLK]
