# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/constrs_1/imports/example_design/ac701_ethernet_rgmii_example_design.xdc

# IP: C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/ac701_ethernet_rgmii/ac701_ethernet_rgmii.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ac701_ethernet_rgmii || ORIG_REF_NAME==ac701_ethernet_rgmii}]

# IP: C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/eth_head_fifo/eth_head_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth_head_fifo || ORIG_REF_NAME==eth_head_fifo}]

# IP: C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/tx_fifo/tx_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tx_fifo || ORIG_REF_NAME==tx_fifo}]

# IP: C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/ip_rx_bram/ip_rx_bram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_rx_bram || ORIG_REF_NAME==ip_rx_bram}]

# IP: C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/blk_mem_gen_v8_3/blk_mem_gen_v8_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_v8_3 || ORIG_REF_NAME==blk_mem_gen_v8_3}]

# IP: C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/udp_wavtx_fifo_w32r8/udp_wavtx_fifo_w32r8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==udp_wavtx_fifo_w32r8 || ORIG_REF_NAME==udp_wavtx_fifo_w32r8}]

# IP: C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/udp_cmdrx_wr8rd32/udp_cmdrx_wr8rd32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==udp_cmdrx_wr8rd32 || ORIG_REF_NAME==udp_cmdrx_wr8rd32}]

# IP: C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/udp_stattx_fifo_wr32r8/udp_stattx_fifo_wr32r8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==udp_stattx_fifo_wr32r8 || ORIG_REF_NAME==udp_stattx_fifo_wr32r8}]
