# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tfbg676-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_targetx/ac701_targetx.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_targetx/ac701_targetx.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:ac701:part0:1.2 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files -quiet {{C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_targetx/ac701_targetx.runs/clkgen_synth_1/clkgen.dcp}}
set_property used_in_implementation false [get_files {{C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_targetx/ac701_targetx.runs/clkgen_synth_1/clkgen.dcp}}]
add_files -quiet {{C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_targetx/ac701_targetx.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp}}
set_property used_in_implementation false [get_files {{C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_targetx/ac701_targetx.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp}}]
add_files -quiet {{C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_targetx/ac701_targetx.runs/blk_mem_gen_1_synth_1/blk_mem_gen_1.dcp}}
set_property used_in_implementation false [get_files {{C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_targetx/ac701_targetx.runs/blk_mem_gen_1_synth_1/blk_mem_gen_1.dcp}}]
add_files -quiet {{C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_targetx/ac701_targetx.runs/blk_mem_gen_2_synth_1/blk_mem_gen_2.dcp}}
set_property used_in_implementation false [get_files {{C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_targetx/ac701_targetx.runs/blk_mem_gen_2_synth_1/blk_mem_gen_2.dcp}}]
add_files -quiet {{C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_targetx/ac701_targetx.runs/srout_bram_blkmem_synth_1/srout_bram_blkmem.dcp}}
set_property used_in_implementation false [get_files {{C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_targetx/ac701_targetx.runs/srout_bram_blkmem_synth_1/srout_bram_blkmem.dcp}}]
read_ip {{C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/ac701_ethernet_rgmii/ac701_ethernet_rgmii.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/ac701_ethernet_rgmii/synth/ac701_ethernet_rgmii_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/ac701_ethernet_rgmii/ac701_ethernet_rgmii.dcp}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/ac701_ethernet_rgmii/synth/ac701_ethernet_rgmii.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/ac701_ethernet_rgmii/synth/ac701_ethernet_rgmii_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/ac701_ethernet_rgmii/synth/ac701_ethernet_rgmii_clocks.xdc}}]
set_property is_locked true [get_files {{C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/ac701_ethernet_rgmii/ac701_ethernet_rgmii.xci}}]

read_ip {{C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/eth_head_fifo/eth_head_fifo.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/eth_head_fifo/eth_head_fifo.dcp}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/eth_head_fifo/eth_head_fifo/eth_head_fifo.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/eth_head_fifo/eth_head_fifo_ooc.xdc}}]
set_property is_locked true [get_files {{C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/eth_head_fifo/eth_head_fifo.xci}}]

read_ip {{C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/tx_fifo/tx_fifo.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/tx_fifo/tx_fifo.dcp}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/tx_fifo/tx_fifo/tx_fifo.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/tx_fifo/tx_fifo_ooc.xdc}}]
set_property is_locked true [get_files {{C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/tx_fifo/tx_fifo.xci}}]

read_ip {{C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/ip_rx_bram/ip_rx_bram.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/ip_rx_bram/ip_rx_bram.dcp}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/ip_rx_bram/ip_rx_bram_ooc.xdc}}]
set_property is_locked true [get_files {{C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/ip_rx_bram/ip_rx_bram.xci}}]

read_ip {{C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/blk_mem_gen_v8_3/blk_mem_gen_v8_3.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/blk_mem_gen_v8_3/blk_mem_gen_v8_3.dcp}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/blk_mem_gen_v8_3/blk_mem_gen_v8_3_ooc.xdc}}]
set_property is_locked true [get_files {{C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/blk_mem_gen_v8_3/blk_mem_gen_v8_3.xci}}]

read_ip {{C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/udp_wavtx_fifo_w32r8/udp_wavtx_fifo_w32r8.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/udp_wavtx_fifo_w32r8/udp_wavtx_fifo_w32r8.dcp}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/udp_wavtx_fifo_w32r8/udp_wavtx_fifo_w32r8/udp_wavtx_fifo_w32r8_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/udp_wavtx_fifo_w32r8/udp_wavtx_fifo_w32r8/udp_wavtx_fifo_w32r8.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/udp_wavtx_fifo_w32r8/udp_wavtx_fifo_w32r8_ooc.xdc}}]
set_property is_locked true [get_files {{C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/udp_wavtx_fifo_w32r8/udp_wavtx_fifo_w32r8.xci}}]

read_ip {{C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/udp_cmdrx_wr8rd32/udp_cmdrx_wr8rd32.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/udp_cmdrx_wr8rd32/udp_cmdrx_wr8rd32.dcp}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/udp_cmdrx_wr8rd32/udp_cmdrx_wr8rd32/udp_cmdrx_wr8rd32_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/udp_cmdrx_wr8rd32/udp_cmdrx_wr8rd32/udp_cmdrx_wr8rd32.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/udp_cmdrx_wr8rd32/udp_cmdrx_wr8rd32_ooc.xdc}}]
set_property is_locked true [get_files {{C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/udp_cmdrx_wr8rd32/udp_cmdrx_wr8rd32.xci}}]

read_ip {{C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/udp_stattx_fifo_wr32r8/udp_stattx_fifo_wr32r8.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/udp_stattx_fifo_wr32r8/udp_stattx_fifo_wr32r8.dcp}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/udp_stattx_fifo_wr32r8/udp_stattx_fifo_wr32r8/udp_stattx_fifo_wr32r8_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/udp_stattx_fifo_wr32r8/udp_stattx_fifo_wr32r8/udp_stattx_fifo_wr32r8.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/udp_stattx_fifo_wr32r8/udp_stattx_fifo_wr32r8_ooc.xdc}}]
set_property is_locked true [get_files {{C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/ip/udp_stattx_fifo_wr32r8/udp_stattx_fifo_wr32r8.xci}}]

read_vhdl -library xil_defaultlib {
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/imports/example_design/common/ac701_ethernet_rgmii_sync_block.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/imports/example_design/common/ac701_ethernet_rgmii_reset_sync.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/imports/example_design/fifo/ac701_ethernet_rgmii_bram_tdp.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/imports/example_design/fifo/ac701_ethernet_rgmii_tx_client_fifo.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/imports/example_design/support/ac701_ethernet_rgmii_support_resets.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/imports/example_design/support/ac701_ethernet_rgmii_support_clocking.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/imports/example_design/fifo/ac701_ethernet_rgmii_rx_client_fifo.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/imports/example_design/fifo/ac701_ethernet_rgmii_ten_100_1g_eth_fifo.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/imports/example_design/support/ac701_ethernet_rgmii_support.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/imports/example_design/ac701_ethernet_rgmii_clk_wiz.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/imports/example_design/ac701_ethernet_rgmii_fifo_block.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/imports/example_design/ac701_ethernet_rgmii_example_design_resets.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/imports/example_design/ac701_ethernet_rgmii_example_design_clocks.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/imports/example_design/axi_lite_sm/ac701_ethernet_rgmii_axi_lite_sm.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ip_udp_tx_block.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ip_udp_rx_block.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/eth_head.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/sources_1/imports/example_design/ac701_ethernet_rgmii_example_design.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/targetx_files/src/asic_interfaces/asic_definitions_irs2_carrier_revA.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/udp.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/targetx_files/src/readout_definitions.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/eth_top.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/targetx_files/src/peripherals/SRAMiface2.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/targetx_files/src/utilities/edge_to_pulse_converter.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/targetx_files/src/PedRAMaccess.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/targetx_files/src/KLM_SCROD_baseline/conc_intfc/source/conc_intfc_pkg.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/targetx_files/src/KLM_SCROD_baseline/klm_scrod/source/klm_scrod_pkg.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/targetx_files/src/KLM_SCROD_baseline/tdc/source/tdc_pkg.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/targetx_files/src/KLM_SCROD_baseline/time_order/source/time_order_pkg.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ethernet_readout_interface.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/targetx_files/src/DigitizingLgcTX.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/targetx_files/src/PedestalManagement.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/targetx_files/src/ReadoutControl3.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/targetx_files/src/SRAMscheduler.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/targetx_files/src/SamplingLgc.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/targetx_files/src/SerialDataRoutDemux.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/targetx_files/src/TARGETX_DAC_CONTROL.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/targetx_files/src/WaveformPedsubDSP.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/targetx_files/src/asic_interfaces/trigger_scalers.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ped_dac_control.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/targetx_files/src/WaveformPedcalcDSP.vhd}
  {C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/targetx_files/src/scrod_top_A5_KLM_9UMB.vhd}
}
read_xdc {{C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/constrs_1/imports/example_design/ac701_ethernet_rgmii_example_design.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Jose Idlabs/Documents/ac701_ethernet_rgmii_example_targetx/ac701_ethernet_rgmii_example.srcs/constrs_1/imports/example_design/ac701_ethernet_rgmii_example_design.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top scrod_top_A5_KLM_9UMB -part xc7a200tfbg676-2 -flatten_hierarchy none
write_checkpoint -noxdef scrod_top_A5_KLM_9UMB.dcp
catch { report_utilization -file scrod_top_A5_KLM_9UMB_utilization_synth.rpt -pb scrod_top_A5_KLM_9UMB_utilization_synth.pb }
